

<header id="INDEX_ID">
    <a class="header_top" href="./ISSUE_4_VOL3.HTML">
      <text>
        <p3>  
            © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES -© TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE - ISSUE 4 CALL FOR NARRATIVES - © TBD ULTRAMAGAZINE
        </p3> 
      </text>
    </a>
    
    <div class="header_lower">
        <div class="header_buttons_container">
            <a class="header_anchor" data-target="#LATEST">
              <p2> 
                  LATEST
              </p2>
            </a>

            <a class="header_anchor" data-target="#ISSUES">
              <p2> 
                  ISSUES
              </p2>
            </a>

            <a class="header_anchor" data-target="#ABOUT">
              <p2> 
                  ABOUT
              </p2>
            </a>
        </div>

        <a style="height: 100%; flex-shrink: 0" href="#">
            <img style="height: 100%;" src="WEBRESOURCES/IDENTITY_IMAGES/tbd_LOGO.webp">
        </a>

        <div class="header_burger_container">

            <div class="slider">
              <div class="black_slider"></div>
              <div class="white_slider"></div>
              <p3 class="IT">IT</p3>
              <p3 class="EN">EN</p3>
            </div>

            <a class="headeranchors" style="align-items: center; vertical-align: middle;">
            <div class="burger-icon">
                <div class="burger-line"></div>
                <div class="burger-line"></div>
                <div class="burger-line"></div>
            </div>
            </a>
        </div>
    </div>
    
</header>